version: '3'

services:
  app:
    image: node:20.15.0-bullseye
    container_name: hotels-app
    command: npm run dev
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
      - 9000:9000
